public enum CharacterState
{
     IDLE, RUNNNING, SINGLE_JUMP, SINGLE_JUMP_RUNNING, DOUBLE_JUMP, PUSHING_IDLE, PUSHING, BALANCE, DEAD, FALLING_IDLE, FALLING_GROUND
}
public enum EnemyState
{
     IDLE, PATROLLING, STUNNED, SPOTED, FOLLOWING_PLAYER, ATTACKING__PLAYER
}