public enum CharacterState
{
    IDLE, RUNNNING, SINGLE_JUMP, SINGLE_JUMP_RUNNING, DOUBLE_JUMP, PUSHING, BALANCE, DEAD, DISABLED
}
public enum EnemyState
{
    IDLE, PATROLLING, STUNNED, FOLLOWING_PLAYER, ATTACKING__PLAYER, DEAD, DISABLED
}