public enum CharacterState
{
     IDLE, RUNNNING, SINGLE_JUMP, SINGLE_JUMP_RUNNING, DOUBLE_JUMP, PUSHING_IDLE, PUSHING, BALANCE, DEAD, DISABLED, GRABBING
}
public enum EnemyState
{
     IDLE, PATROLLING, STUNNED, FOLLOWING_PLAYER, ATTACKING__PLAYER, DEAD, DISABLED
}